language: node_js
branches:
    only:
        - master
cache:
    diretories:
        - node_modules
notifications:
    email: true
node_js:
    - node
before_script:
    - npm prune
script:
    - npm run build
